### ISSUE TITLE
Compatibility with Per-Camera Resolution

### ISSUE THREAD

**Issue by JR3DFUL** [samytichadou/render_preset_blender#2]
Compatibility with the [Per-Camera Resolution](https://projects.blender.org/pioverfour/per_camera_resolution) addon would be a massive time saver, allowing for not only resolutions but other render settings as well.

**Comment by samytichadou** [comment]
thanks for the idea, after tested the addon, i'm not sure about the implementation.
The addon changes dynamically the scene resolution when a camera is set as active, according to the per camera resolution properties.
Render preset can't save a specific camera properties, if the user tries to apply the render preset in another scene, the camera would not be found and the preset would fail.
Giving the per camera addon set the scene resolution, i don't really get what the preset could save.
Would you care to explain what are your expectations about this feature ?
thanks

**Comment by samytichadou** [comment]
Closing for lack of infos
